export const LOG_EVENTS = {
  // Server events
  SERVER_STARTED: 'SERVER_STARTED',
  SERVER_SHUTDOWN: 'SERVER_SHUTDOWN',
  SERVER_CLOSED: 'SERVER_CLOSED',
  SERVER_ERROR: 'SERVER_ERROR',

  // RSS events
  RSS_FETCH_STARTED: 'RSS_FETCH_STARTED',
  RSS_FETCH_COMPLETED: 'RSS_FETCH_COMPLETED',
  RSS_FETCH_ERROR: 'RSS_FETCH_ERROR',
  RSS_FEED_FETCHED: 'RSS_FEED_FETCHED',
  RSS_FEED_ERROR: 'RSS_FEED_ERROR',
  RSS_AGGREGATION_COMPLETED: 'RSS_AGGREGATION_COMPLETED',

  // Cache events
  CACHE_MISS: 'CACHE_MISS',
  CACHE_HIT: 'CACHE_HIT',
  CACHE_SET: 'CACHE_SET',

  // Scheduler events
  SCHEDULER_STARTED: 'SCHEDULER_STARTED',
  SCHEDULER_STOPPED: 'SCHEDULER_STOPPED',
  SCHEDULER_JOB_EXECUTED: 'SCHEDULER_JOB_EXECUTED',
  SCHEDULER_JOB_ERROR: 'SCHEDULER_JOB_ERROR',

  // HTTP events
  HTTP_REQUEST: 'HTTP_REQUEST',
  HTTP_ERROR: 'HTTP_ERROR',

  // Use case events
  USE_CASE_EXECUTED: 'USE_CASE_EXECUTED',
  USE_CASE_ERROR: 'USE_CASE_ERROR',
} as const;

